Added custom_vars to package config.
Windows and Mac need to have a custom_var set to download PGO profiles,
otherwise an error occurs:

RuntimeError: requested profile "src\chrome\build\pgo_profiles\chrome-win64-4183-1594749420-42c1e48a5856e3cacd3f686e3783fc7d133f85cb.profdata" doesn't exist, please make sure "checkout_pgo_profiles" is set to True in the "custom_vars" section of your .gclient file, e.g.:
solutions = [
  {
    "name": "src",
    # ...
    "custom_vars": {
      "checkout_pgo_profiles": True,
    },
  },
],
and then run "gclient runhooks" to download it. You can also simply disable the PGO optimizations by setting |chrome_pgo_phase = 0| in your GN arguments.

Chromium changes:

https://chromium.googlesource.com/chromium/src/+/b3a683e65769a22bee63d16c493d7adb746178d5

commit b3a683e65769a22bee63d16c493d7adb746178d5
Author: Yuke Liao <liaoyuke@chromium.org>
Date:   Wed Apr 29 01:43:59 2020 +0000

    Reland "Add runhooks to download PGO profiles and allow query profile path"

    This is a reland of 5f5008fc7536c6f18b6099cb63675882a7b896e9

    Original change's description:
    > Add runhooks to download PGO profiles and allow query profile path
    >
    > This CL:
    > 1. Adds gclient runhooks to download PGO profiles.
    > 2. Allows the build system to query the path to the current profile.
    >
    > Bug: 1071576

https://chromium.googlesource.com/chromium/tools/build/+/7a46a7a2c882f12968b5284c25acc9f3b5ed11a6

commit	7a46a7a2c882f12968b5284c25acc9f3b5ed11a6
Author:	Stephanie Kim <kimstephanie@google.com>
Date:   Thu Jul 09 00:14:00 2020

    checkout_pgo_profiles for windows official builders

    PGO is enabled by default for these windows builders because it runs with
    the is_official_build=True gn arg. So, it needs the checkout_pgo_profiles
    gclient config. Without it, the build fails with this error: https://ci.chromium.org/p/chromium/builders/ci/win32-official/26

    Bug: 1072012